### ISSUE TITLE
textfield.zpt is missing in tests

### ISSUE THREAD

**Issue by sammakkoinen** [niner/CiderCMS#2]
The following tests:
- controller_Content-Management.t 
- controller_Content_env_instance.t 
- move.t 
- paste.t 

fail with error: `could not copy template textfield.zpt`
Steps to reproduce: 
- download the CiderCMS-master.zip distribution from github and unzip it, cd CiderCMS-master
- perl Makefile.PL; make; make test

This can be fixed by adding the required file textfield.zpt to./t/test.example/templates/types/ (I have copied it from textarea.zpt), but I'm not sure if either the file is missing from the distribution or the tests are obsolete.

**Comment by niner** [comment]
Fixed in commit 1d794aff95807836eed0f072dbc05ed79d5db71e

Thanks for the report!
